name: GitHub Classroom Workflow

on: 
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: .github/classroom/countissues.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: education/autograding@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


